# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fristName', models.CharField(max_length=50)),
                ('client_lastName', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=100)),
                ('client_PostCod', models.CharField(max_length=6)),
                ('client_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_label', models.CharField(max_length=50)),
                ('dealer_url', models.CharField(max_length=200)),
                ('dealer_addresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealermarketsApp.Dealer'),
        ),
    ]
