# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealermarketsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_fristName',
            new_name='client_firstName',
        ),
    ]
