# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealermarketsApp', '0002_auto_20170802_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_PostCod',
            field=models.CharField(max_length=7),
        ),
    ]
